# 1] Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.


In [1]:
from sklearn.datasets import load_iris

In [2]:
data=load_iris()
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
import pandas as pd
import numpy as np

In [4]:
X=data.data
y=data.target

In [5]:
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier()

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=129)

In [8]:
clf.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred=clf.predict(X_test)

# 2] Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.


In [10]:
df=pd.read_csv("Boston.csv",usecols=["crim","zn","indus","chas","nox","rm","age","dis","rad","tax","ptratio","black","lstat","medv"])
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [11]:
df.shape

(506, 14)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [13]:
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor()

In [14]:
X=df.drop(columns=["medv"])
y=df["medv"]

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=129)

In [16]:
model.fit(X_train,y_train)

KNeighborsRegressor()

In [17]:
y_pred=model.predict(X_test)

In [18]:
from sklearn.metrics import mean_squared_error,r2_score 

In [19]:
mean_squared_error(y_test,y_pred)

45.65511764705882

In [20]:
r2_score(y_test,y_pred)

0.5019309895545521

# 3] Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [21]:
from sklearn.model_selection import cross_val_score,KFold

In [22]:
k_values=range(2,31)
cv_scores=[]
independent_features=data.data
dependent_feature=data.target
def optimumValueOfK():
    for k in k_values:
        knn=KNeighborsClassifier(n_neighbors=k)
        
        kf=KFold(n_splits=5,shuffle=True,random_state=42)
        scores=cross_val_score(knn,independent_features,dependent_feature,cv=kf,scoring="accuracy")
        cv_scores.append(scores)
    return cv_scores

In [23]:
best_k=k_values[np.argmax(optimumValueOfK())]
best_k

2

# 4] Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets. 


In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [25]:
scaler.fit_transform(X_train,y_train)

array([[8.18254447e-05, 7.89473684e-01, 1.29765396e-01, ...,
        9.04255319e-01, 1.00000000e+00, 3.57281553e-01],
       [2.74610913e-02, 0.00000000e+00, 7.00879765e-01, ...,
        2.23404255e-01, 8.31408543e-01, 2.60748960e-01],
       [1.42423481e-02, 0.00000000e+00, 7.00879765e-01, ...,
        2.23404255e-01, 8.53799990e-01, 9.93065187e-02],
       ...,
       [3.06508225e-04, 7.89473684e-01, 9.12756598e-02, ...,
        6.06382979e-01, 9.96772404e-01, 1.66435506e-03],
       [5.13252350e-03, 0.00000000e+00, 2.10410557e-01, ...,
        5.10638298e-01, 9.47652428e-01, 9.23717060e-02],
       [1.30066490e-03, 0.00000000e+00, 8.90762463e-02, ...,
        5.74468085e-01, 9.01860911e-01, 1.31206657e-01]])

In [26]:
model.fit(X_train,y_train)

KNeighborsRegressor()

In [27]:
y_pred1=model.fit(X_train,y_train)

In [28]:
mean_squared_error(y_test,y_pred)

45.65511764705882

In [29]:
r2_score(y_test,y_pred)

0.5019309895545521

# 5] Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.


In [30]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))


In [31]:
def weighted_knn_classifier(X_train, y_train, X_test, k=3):
    num_test_samples = X_test.shape[0]
    y_pred = np.zeros(num_test_samples, dtype=int)

    for i in range(num_test_samples):
        # Calculate distances from the test sample to all training samples
        distances = np.array([euclidean_distance(X_train[j], X_test[i]) for j in range(X_train.shape[0])])

        # Sort the distances and get the indices of the k nearest neighbors
        k_nearest_indices = np.argsort(distances)[:k]

        # Calculate the weighted votes based on the inverse of distances
        weights = 1.0 / distances[k_nearest_indices]
        
        # Get the corresponding labels of the k nearest neighbors
        k_nearest_labels = y_train[k_nearest_indices]

        # Perform weighted voting to determine the predicted label for the test sample
        weighted_votes = np.bincount(k_nearest_labels, weights=weights)
        y_pred[i] = np.argmax(weighted_votes)

    return y_pred

In [32]:
X=data.data
y=data.target

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=129)

In [34]:
y_pred2=weighted_knn_classifier(X_train,y_train,X_test)
y_pred2

/tmp/ipykernel_4018/33551776.py:13: RuntimeWarning: divide by zero encountered in divide
  weights = 1.0 / distances[k_nearest_indices]


array([0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 1, 0, 1, 0, 2, 1, 1, 0, 2, 1, 0, 2,
       1, 1, 2, 0, 2, 2, 0, 0])

# 6] Implement a function to standardise the features before applying KNN classifier.


In [35]:
df=pd.DataFrame(data.data)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [36]:
df.describe().T

count      mean       std  min  25%   50%  75%  max
0  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
1  150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
2  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
3  150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [37]:
def featureScaler(feature):
    feature=np.array(feature)
    mean=np.mean(feature)
    std=np.std(feature)
    return (feature - mean) / std

In [38]:
for i in range(0,4):
    df[i] = featureScaler(df[i])
df.describe().T

count          mean      std       min       25%       50%       75%  \
0  150.0 -4.736952e-16  1.00335 -1.870024 -0.900681 -0.052506  0.674501   
1  150.0 -7.815970e-16  1.00335 -2.433947 -0.592373 -0.131979  0.558611   
2  150.0 -4.263256e-16  1.00335 -1.567576 -1.226552  0.336478  0.762758   
3  150.0 -4.736952e-16  1.00335 -1.447076 -1.183812  0.132510  0.790671   

        max  
0  2.492019  
1  3.090775  
2  1.785832  
3  1.712096

# 7] Write a Python function to calculate the euclidean distance between two points.


In [39]:
def euclideanDistance(x1,x2):
    return np.sqrt(np.sum((x1 - x2)**2))

# 8] Write a Python function to calculate the manhattan distance between two points.

In [40]:
def manhattanDistance(x1,x2):
    return np.sum(np.abs(x1 - x2))
